name: 'Junius Test Action'
description: 'Junius Test Action'
inputs:
  username:
    description: 'username'
    required: true
    default: 'Junius'
runs:
  using: "composite"
  env:
    USERNAME: ${INPUT_USERNAME}
  steps:
    - run: echo Hello from ${USERNAME}
      shell: bash