name: 'Junius Test Action'
description: 'Junius Test Action'
inputs:
  username:
    description: 'username'
    required: true
    default: 'Junius'
runs:
  using: actions/checkout@v2
  using: "composite"
  steps:
    - env:
      - INPUT: ${{inputs.username}}
    - run: env
      shell: bash
    - run: echo Hello with ${{inputs.username}}
      shell: bash