name: 'Junius Test Action'
description: 'Junius Test Action'
inputs:
  username:
    description: 'username'
    required: true
    default: 'Junius'
runs:
  steps:
    - run: echo Hello from $INPUT_USERNAME
      shell: bash