name: 'Junius Test Action'
description: 'Junius Test Action'
inputs:
  username:
    description: 'username'
    required: true
    default: 'Junius'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        path: ./action-project/
    - run: env
      shell: bash
    - run: echo Hello with ${{inputs.username}}
      shell: bash